services:
  vw-tracker:
    image: ghcr.io/subasically/vw-tracker
    container_name: vw-tracker
    platform: linux/amd64 # or linux/arm/v7 or linux/arm64
    ports:
      - "8123:8000"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - PAUSE_INTERVAL=${PAUSE_INTERVAL}
      - REFRESH_TOKEN_INTERVAL=${REFRESH_TOKEN_INTERVAL}
    volumes:
      - ./static:/app/static
    command: ["python", "app.py"]