services:
  vw-tracker:
    image: ghcr.io/subasically/vw-tracker:latest
    container_name: vw-tracker
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    command: ["python", "app.py"]