services:
  vw-tracker:
    image: ghcr.io/subasically/vw-tracker
    container_name: vw-tracker
    platform: linux/amd64 # or linux/arm/v7 or linux/arm64
    ports:
      - "8123:8123"
    environment:
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      - UPDATE_INTERVAL=900
      - PAUSE_INTERVAL=1800
      - REFRESH_TOKEN_INTERVAL=3600
      - VEHICLE_NAME=My Car
      - SMARTCAR_REDIRECT_URI=http://localhost/smartcar/redirect/
    volumes:
      - ./static:/app/static
    command: ["python", "app.py"]