services:
  vw-tracker:
    image: ghcr.io/subasically/vw-tracker
    container_name: vw-tracker
    ports:
      - "8123:8123"
    environment:
      - CLIENT_ID=123
      - CLIENT_SECRET=abc
      - SMARTCAR_REDIRECT_URI=http://localhost/smartcar/redirect/
      - UPDATE_INTERVAL=900
      - PAUSE_INTERVAL=1800
      - REFRESH_TOKEN_INTERVAL=3600
      - VEHICLE_NAME=My Car
    volumes:
      - ./static:/app/static
    command: ["python", "app.py"]